---
title: 'Wandern im Himalaya (3)'
author: 'Tim Hagmann'
date: '2018-11-07'
slug: himalaya-2
categories: []
tags: [Lukla, Himalaya, Wanderung, Pangboche, Pheriche, Thukla, Lobuche, Gorakshep, EVBC]
subtitle: ''
---

#### Gorakshep - EVBC - Lobuche (11. November)
Heute ist der grosse Tag, es geht auf zum Everest Base Camp. Wie üblich wachen wir mit Kopfschmerzen und Schwindel auf, wir gehen es langsam an und starten um 09:00 zu unserer Wanderung zum Basecamp. Diese führt uns über den Kumbu (Everest) Gletscher über eine grosse Moräne hin zum Base Camp. Der Gletscher ist massiv und mit steinen Überdeckt. Geologisch ist dies sehr interessant, ästhetisch leider nicht. Der Streckenabschnitt ist der am wenigsten schöne während unserer Wanderung. Dennoch bleibt die Wanderung nicht ohne Highlight, denn nach 2/3 des Weges zeigt der Mount Everest sein Gesicht. Diesen haben wir seit Namche Bazaar nicht mehr gesehen, da die Anderen Berge diesen verdecken. Nach ein paar obligaten Fotos ziehen wir weiter.

Um 10:30 kommen wir an dem 11. Tag unserer Wanderung in guter Stimmung an unserem Ziel, dem Everest Base Camp auf 5380m an. Wir verbringen fast eine Stunde auf diesem Punkt, was Manraj aufgrund der Höhenkrankheit leicht nervös macht. Wir machen uns somit wieder an den Abstieg und wandern den Weg via Gorakshep zurück bis Lobuche. 

#### Lobuche - Thukla - Pheriche - Pangboche (12. November)
Es geht heimwärts. Es gilt den Weg welchen wir in 11 Tagen erklommen haben in 4 Tagen wieder zurückzuwandern. Am 16. November geht unser Flieger in Lukla. Dies bedeut lange Wandertage. Zum ersten Mal seit dem Wandern findet sich die Anstrengung nicht in der Höhe sondern in den Beinen wieder. Das Tolle ist allerdings, dass wir erneut die spektakuläre Landschaft geniessen können. Wir sehen die alten Bekannten wie Ama Dablam wieder. Nicht dass nun alles runterwärts geht. Nepals Berge zeichnen sich wie schon beschrieben durch ein stetiges auf und ab aus. Wir starten in Lobuche in der Höchsten Bäckerei der Welt und kaufen uns einen Karottenkuchen. Die Stärkung hilft uns und wir wandern leichten Fusses beim Everest Denkmal vorbei, der gefürchige Brücke von Thukla passieren wir ebenfalls entspannt und kommen in Pheriche pünktlich zur Mittagszeit an. Nach einer kleinen Pause geht es anschliessend weiter bis Pangboche. Dem Ort an welchem Miri mit der Höhenkrankheit zu kämpfen hatte. Wir merken beide, dass uns der Abstieg gut tut und es uns besser und besser geht. Auf 4000m atmet es sich sehr viel leichter als zuvor. Nach einem obligaten Kartenspiel und einem leckeren Abendessen verkriechen wir uns gegen 21:00 langsam in unseren Schlafsäcken.

#### Pangboche - Tengboche - Kyanjuma (13. November)
Der 13. November zeigt sich von seiner kalten Seite. So kalt, dass der Atem auf dem Buff gefriert. Es hilft allerdings alles nichts, wir müssen weiter, denn am 16. November geht unser Flug. Unsere Route führt uns den steilen Hang zum Kloster von Tengboche hoch. Dieses erreichen wir um 11:00 und bestaunen die Gebetsräume der Mönche. Es ist beeindruckend was für Architektur auf 4000m über dem Meer möglich ist. Nach einem kurzen Aufenthalt machen wir uns auf zum Abstieg tief ins Tal. Heute gilt es 600m bis tief zum Fluss zu wandern um anschliessend wieder 400m aufzusteigen. Zur Lunchzeit in Phungi Thanga treffen wir zwei Kanadier aus Montreal und unterhalten uns über die Kälte. Diese erzählen uns, dass Montreal im Winter gut und gerne -30 Grad aufweist. Wir sind trotzdem froh, dass wir am Absteigen sind und die Temperaturen nun langsam steigen sollten. Gegen den späten Nachmittag haben kommen wir Kyanjuma (3700m) unserem Übernachtungsort an. Zu unseren Freuden gibt es wieder eine hauseigene Bäckerei. Wir entschliessen uns den Wasserporridge für den nächsten Tag sausen zu lassen und stattdessen etwas aus der Bäckerei fürs Frühstück zu wählen. 

#### Kyanjuma - Namche - Jorsalle - Phakding  (14. November)
Gestärkt durch 

#### Phakding - Lukla (15. November)

#### Rückflug (16. November)

#### Ruhetage in Kathmandu (17. & 18. November)

#### Chitwan 
Bären, Krokodile, Nasshörner.

#### Bhaktapur
Vollmondfestival, Christine, Ramej,


#### Chengdu
Am 24. November fliegen wir nach Chengdu, China. Wir werden in ein Taxi verfrachtet und machen uns auf den Weg zum Flughafen in Kathmandu. Dort angekommen stellen wir fest, dass wir noch einiges an Mineralwasser dabei haben. Beim Nachfragen beim Sicherheitsbeamten erhalten wir die Antwort: Wasser? ... Ja natürlich kann man Wasser mitnehmen :) Wir decken uns mit Old-School Süssigkeiten am Flughafen ein und machen uns ans Check-in. Dort stellen wir fest, dass chinesische Airlines das Fliegen ein wenig anders zu handhaben scheinen als die uns bekannten Airlines. Nicht nur unser Gepäck sondern auch wir erhalten einen Aufkleber. Leider scheinen die Chinesen allerdings genauso unter Verspätungen zu leiden wie die Westlichen Airlines. Der Flug wir Stunde um Stunde nach hinten verschoben. Nach 4 Stündigen Warten können wir endlich den Flug via Tibet nach Chengdu boarden. In der Luft kommt jedoch die nächste Überraschung. Aufgrund von schlechtem Wetter entscheidet der Pilot nun doch direkt nach Chengdu zu fliegen. Uns soll es recht sein, wenn uns auch die Passagier nach Lhasa leid tun. Als Entschuldigung für die Unannehmlichkeiten erhalten alle Passagiere eine Popcorn Schnitte. 

In Chengdu angekommen fahren wir via Metro ins Stadtzentrum. Wir haben über eine Freundin einer Freundin eine Bekannte (Joanna) vermittelt bekommen, bei welcher wir übernachten können. Mit schrecken mussten wir allerdings feststellen, dass sämtliche üblichen Kommunikationskanäle in China gesperrt sind. Wir suchen verzweifelt ein offenes WLAN Netz. In der Metro richtet uns ein netter Chinese einen Hotspot ein, dank welchen wir Joanna kontaktieren können. Das Treffen mit ihr bei einem grossen Einkaufszentrum klappt gut uns wir gehen gemeinsam mit ihr nach Hause. Zu unserer Überraschung ist die Wohnung grösser als unsere Erwartung mit einem extra Schlafraum für uns.

Da unsere Mägen ziemlich am knurren sind, machen wir uns gemeinsam mit Joanna auf den Weg für einen späten Gutenachtsnack. Wir lassen uns in ein Chinesisches BBQ Restaurant führen und essen unser erstes sehr leckeres Chinesisches Abendessen. Anschliessend schlaen wir erschöpft ein.

Joanna nimmt sich am nächsten Tag Zeit für uns und nachdem wir alle ausgeschlafen haben machen wir uns auf den Weg zum Brunchen bei Wagas. Dies ist eine Art Chinesischer Starbucks bei welchem wir leckeren Tee und ein langersehntes Westliches Frühstück essen. Anschliessend geht es auf zu einem Buddistischen Tempel welcher sich in einem grossen offenen Einkaufszentrum befindet. Lustigerweise treffen wir auf eine grosse Gruppe von Chinesischen jungen Erwachsenen für welche nicht der Tempel sondern wir die Attraktion darstellen. Nach vielen gemeinsamen Fotos können wir uns losreissen und besichten den Tempel. Anschliessend besichtigen wir ein riesiges Chinesisches Einkaufszentrum. Dies da wir gerne das "echte" Leben von Chinesen kennenlernen möchten. Das Einkaufszentrum errinert uns stark an die USA. Dies da neben unzähligen westlichen Marken auch eine Iceskating Halle vorhanden ist. Anschliessend gehen zum Abendessen in ein Veganes Hotpot Restaurant. Hotpot entspricht mehr oder weniger dem Fondue Chinoise.

Der nächste Tag ist den Pandabären gewidmet. Da Joanna arbeiten muss, machen wir uns dieses mal alleine am späteren Morgen auf den Weg zu knuffigen schwarzweissen Bären. Die Pandabär Research Station in Chengdu ist riesig und widmet sich der Aufzucht von Pandabären um diese vor dem Aussterben zu bewaren. Wir verbringen fast den ganzen Tag in der Research Station und bestaunen die Bären welche von kleinen knuffigen Bärchen zu einer respektablen Grösse heranwachsen. Anschliessend gehen wir mit Joanna in einem Kantonesischen Restaurant Abendessen. Den Rest des Abends verbringen wir bei Joanna mit Wein, Schockolade und spannenden Gesprächen. Da wir am nächsten Tag bereits um 03:00 das Taxi zum Flughafen nehmen müssen, wir die Nacht mit nur 1.5 Stunden Schlaf eher kurz. Denoch schaffen wir es uns aus dem Bett zu quälen und fliegen pünklicht Richtung Hualong Airport. Wir haben nämlich vor den Juozhaigo Nationalpark (45 Flugminuten nördlich von Chengdu) zu besichten. Wir kommen um 07:00 auf 2800 Metern über mehr mit Schnee auf der Fahrbahn in den sehr kalten Chinesischen Bergen an. Mit Schrecken werden wir aber von den versammelten Taxifahrern informiert, dass der Nationalpark aufgrund von einem Erdbeben gesperrt ist. Das von uns gebuchte Hotel scheint auch keinen funktionierenden Telefonanschluss zu haben...

#### Huolong Nationalpark
... Wir treffen ein sehr nettes Chinesisches Pärchen am Flughafen welche uns erzählen, dass sie gerne mit uns ein Taxi teilen. Es gäbe einen andern Nationalpark in der nähe, welcher ebenfalls sehr schön sei. Nachdem die beiden mit dem Taxifahrer einen guten Preis verhandelt haben, machen wir uns auf den Weg zum Huolong Nationalpark. Nach 30' Fahrt stehen wir vor einen Gondelstation. Die Gondel bringt uns auf 3500m Höhe. Nach einer kurzen 45' Wanderung kommen wir beim beeindruckenden Nationalpark welcher aus mehreren Naturgeformten Becken besteht an. Interessanterweise ist der Nationalpark sehr gut mit öffentlichem WLAN erschlossen. Dies ermöglicht es uns das gebuchte Hotel zu Canceln sowie einen Rückflug einen Tag früher nach Chengdu zu buchen. Anschliessend an das Buchen lernen wir ein weiteres Chinesisches Pärchen kennen. Diese wollten eigentlich ebenfalls den Juozhaigou Nationalpark besichtigen und wurden gleich wie wir von dem Erdbeben überrascht. Unsere kleine Gruppe besteht nun aus 6 Personen. Die 4 Chinesen nehmen uns unter ihre Fitiche und wir lernen erneut die Chinesische Gastfreundschaft kennen. Sie laden uns nähmlich während den njächsten Tagen jeweils zum Abendessen ein. Ihnen scheint es auch sehr wichtig zu sein, dass wir verschiedenste Chinesische Spezialitäten probieren können. Leider mundet uns nicht immer alles und wir müssen einen grossen Teil von der servierten Fischsuppe leider stehen lassen. Das Hotel am Abend ist günstig und leider auch nicht besonders toll. Wir sind aber froh ein warmes Dach in der Kälte zu haben und schlaffen erschöpft ein.

#### Songpan & Mouni Valley
Am nächsten Morgen geht es dem jüngeren Chinesischen Pärchen leider aufgrund der Höhe nicht besonders gut und sie müssen im Hotel bleiben. Wir machen uns auf den Weg die Stadt Songpan zu besichtigen. Songpan ist eine ehemallige Grenzstadt welche eine gut erhaltene Innenstadt sowie eine fantastische Stadtmauer besistzt. Nach einem Frühstück bestehend aus Chinesischen Dumplings (Raviolis) besichtigen wir die Stadt. Anschliessend machen wir uns auf den Weg zum Mouni Valley, einem weiteren Nationalpark, um dort ein bisschen rumzuwandern. Das Mouni Valley besteht aus einem tollen Wasserfall sowie wunderschönen Teichen und einer grossen Parkanlage. Anschliessend machen wir uns auf den Weg zurück nach Songpan und essen dort einen Hotpot. Die Chinesen möchten für uns einen vielzahl von Innereien wie Kutteln, Schweinefüsschen, Zunge, sowie Rindshirn bestellen. Die Chefin im Restaurant weigert sich allerdings, da sie der Meinung ist, dass das standart Hotpot Menu bereits aus genug zutaten besteht und wir schon genug Mühe hätten dieses aufzuessen. Wir sind sehr erleichtert und geniessen das reguläre Fleisch und Gemüsefondue. Anschliessend machen wir uns auf den Heimweg da wir am nächsten Tag bereits wieder früh zurück nach Chengdu fliegen um am gleichen Tag der Hochgeschwindigkeitszug nach Xi'an zu nehmen.

#### Xi'an
Die Anreise nach Xi'an verläuft wie am Schnürchen. Wir sind begeistert von dem Hochgeschwindigkeitszug welcher uns für 25 Euro (30 Franken) in 4 Stunden von Chengdu durch das halbe Land nach Xi'An bringt. In der ehemaligen Kaiserstadt xi-An werden wir von Uschi, einer gu


Während die beiden mit dem Taxifahrer verhandeln, canceln wir unsere  Onlinebuchung 
Joanna Am nächsten morgen um 03:00 müssen






