baseurl = "https://www.miri-und-tim.com/"
DefaultContentLanguage = "de"
title = "Miri & Tim's Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
#pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "miri-und-tim"
googleAnalytics = "UA-127858002-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[Params]
  subtitle = "Everything is Going to be Alright"
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "2. January 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  gcse = "011950318429351382875:ybekbczc7jg" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  #src = "img/banner.jpg"
  #src = "/img/couple.jpg"
  src = "/img/header.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Miri & Tim"
  website = "https://www.miri-und-tim.com/"
  #email = ""
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  #gitlab = "username"
  twitter = "timhagmann"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/number/name"
  #snapchat = "username"
  instagram = "bigblure"
  youtube = "user/timhagmann" # or channel/channelname
  github = "greenore"
  facebook = "tim.hagmann"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

[[menu.main]]
    name = "Reiseroute"
    url = "page/reiseroute/"
    weight = 1

[[menu.main]]
    name = "Über uns"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
    
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 4

[[menu.main]]
    parent = "blog"
    name = "Nepal"
    url = "page/nepal/"
    weight = 1

[[menu.main]]
    parent = "blog"
    name = "Tasmanien"
    url = "page/tasmanien/"
    weight = 2

[[menu.main]]
    parent = "blog"
    name = "Neuseeland"
    url = "page/neuseeland/"
    weight = 3
